const assets = [
  {
    id: '0ebf2aad-3ac3-4274-9710-d4aaf455636f',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'BIIB',
    name: 'Biogen Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'ce4833e1-c561-492a-aace-7eb451d09e02',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'AMAT',
    name: 'Applied Materials, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '7658b394-4296-4b6c-b3e5-02243499faf6',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'CEG',
    name: 'Constellation Energy Corporation Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'a2b0a751-7f99-4de9-b58b-803ff9536d04',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'TEAM',
    name: 'Atlassian Corporation Class A Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'de1307a8-9013-4c38-9f6f-e9df73902b41',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'SIRI',
    name: 'Sirius XM Holdings Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: false,
    easy_to_borrow: false,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '5098a4d2-0917-4184-862c-17dbefde2ed4',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'REGN',
    name: 'Regeneron Pharmaceuticals, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '2506e58c-1f7c-42a5-9bb9-cd0fd6645fd0',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'CSGP',
    name: 'CoStar Group, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '9ed08266-0b97-4dab-bca3-b3faac765787',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'AZN',
    name: 'AstraZeneca PLC American Depositary Shares',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'a62e1ba1-af52-411b-ab22-537c2cd2e67d',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'TTD',
    name: 'The Trade Desk, Inc. Class A Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '7f9df478-237c-45c8-bc80-c97a53478c37',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'TMUS',
    name: 'T-Mobile US, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'b297eda9-133d-4f92-80ff-9e55f7c8ee8b',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'VRSK',
    name: 'Verisk Analytics, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '357a8404-f368-40a1-9356-3eb500f4f08a',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'VRTX',
    name: 'Vertex Pharmaceuticals Incorporated Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '152daa56-fc67-4627-b283-89405b4360fb',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'XEL',
    name: 'Xcel Energy Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '8b059378-e1d0-422c-b80e-157b34700dd6',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'ZS',
    name: 'Zscaler, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '7b7466c4-5066-4e3e-80e6-8da1c835ce56',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'PEP',
    name: 'PepsiCo, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '8ccae427-5dd0-45b3-b5fe-7ba5e422c766',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'TSLA',
    name: 'Tesla, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 50,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '46502bdb-1f73-48cd-a9e7-e194d1d6938d',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'TTWO',
    name: 'Take-Two Interactive Software, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '440efabf-b53c-4d70-b6e5-abb4f53e7104',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'TXN',
    name: 'Texas Instruments Incorporated Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '9ec078b1-5167-4d3d-908c-a1e49be367f1',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'CSCO',
    name: 'Cisco Systems, Inc. Common Stock (DE)',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '55ed1ba5-6299-42a2-809a-50f8a4bd354b',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'CDW',
    name: 'CDW Corporation Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '009c65c9-8abe-49b9-b481-dfeecb67d116',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'FAST',
    name: 'Fastenal Company Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '26226278-b62c-47ec-a1bd-cf0dbd14b420',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'CRWD',
    name: 'CrowdStrike Holdings, Inc. Class A Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'f93d78b0-c2ec-4d9c-bcae-ca77ebce4844',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'FANG',
    name: 'Diamondback Energy, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '21a5e17d-c566-4f1b-8c25-0a505ba37478',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'EXC',
    name: 'Exelon Corporation Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '29e34616-a842-4a30-908c-32eddd0c7e23',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'PCAR',
    name: 'PACCAR Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'ee289c17-ee75-4d48-a9ee-505156d93171',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'CDNS',
    name: 'Cadence Design Systems, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'c5bbc0b0-e2ce-40cd-9974-a4d2ffd201a9',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'WBA',
    name: 'Walgreens Boots Alliance, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '6082378d-ba94-4bb7-a49e-ebe714131ca8',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'ASML',
    name: 'ASML Holding N.V. New York Registry Shares',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '04f7d8b3-3c40-4e19-ab08-aff850458676',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'WDAY',
    name: 'Workday, Inc. Class A Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '5ddc1e60-daca-45da-b2de-f3ee597e60bc',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'CMCSA',
    name: 'Comcast Corporation Class A Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '5e255d55-471d-45fc-ad7a-65c904018bf2',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'ODFL',
    name: 'Old Dominion Freight Line, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '63595036-ec71-4cd5-9979-4997252d23f6',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'MNST',
    name: 'Monster Beverage Corporation',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'fc6a5dcd-4a70-4b8d-b64f-d83a6dae9ba4',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'META',
    name: 'Meta Platforms, Inc. Class A Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'bd10e4a3-a39d-4726-91cd-8b4d68a635ab',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'MAR',
    name: 'Marriott International Class A Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '6b447474-ec1e-4de4-a520-4ecd98694ebf',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'EA',
    name: 'Electronic Arts Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'e02df0be-fd3a-4762-b4c1-c274784bf756',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'ISRG',
    name: 'Intuitive Surgical, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'b93e6816-bac6-4239-b598-0850d12378df',
    class: 'us_equity',
    exchange: 'NYSE',
    symbol: 'DXC',
    name: 'DXC Technology Company',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'df014db2-72a2-4686-be56-e3cdc15efb71',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'KHC',
    name: 'The Kraft Heinz Company Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'af70d056-9fbb-4df4-ad27-3977bd3a9b47',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'GFS',
    name: 'GlobalFoundries Inc. Ordinary Shares',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: false,
    easy_to_borrow: false,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '76875bee-ba49-437b-9d94-e4bf1277249f',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'GEHC',
    name: 'GE HealthCare Technologies Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'd0d63992-2d20-4f63-aa62-30cf76fb3204',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'DLTR',
    name: 'Dollar Tree Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '37f1fb30-cffa-4c00-8776-22ddd6563bb3',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'CCEP',
    name: 'Coca-Cola Europacific Partners plc Ordinary Shares',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '90e9c946-6323-49a4-be69-116f04fec288',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'AEP',
    name: 'American Electric Power Company, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'a21ecb08-ff55-4c19-94d3-a8d607d91be8',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'ADSK',
    name: 'Autodesk, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'd48dfc03-80c7-4054-a3b1-e41bbfe2a92f',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'ANSS',
    name: 'ANSYS, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '6ca2e51d-21df-4ff0-a134-abfdbe084142',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'ADP',
    name: 'Automatic Data Processing, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'c8899fc1-c3b2-411c-a940-4b9380a09b84',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'WBD',
    name: 'Warner Bros. Discovery, Inc. Series A Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '113d6f5b-a48f-4d20-a63f-79ea0bc88ebd',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'DDOG',
    name: 'Datadog, Inc. Class A Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '3302e560-6d33-4ad5-a429-4d573e26962c',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'CPRT',
    name: 'Copart, Inc. (DE) Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'e72fbd29-be6b-43c2-80c6-b6e80d5b23db',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'ADI',
    name: 'Analog Devices, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'fa8500c0-9022-4a74-97f9-93d41ed28dac',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'SNPS',
    name: 'Synopsys, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '5453d1f0-0efc-4738-b1b1-d330e5910e2f',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'DASH',
    name: 'DoorDash, Inc. Class A Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '0cf42aa3-9816-4f1f-aa84-6482ac9303e9',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'INTC',
    name: 'Intel Corporation Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'cd1347d7-8add-49bd-acd1-4ffde9a4081b',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'INTU',
    name: 'Intuit Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '24cbba8c-831b-44e2-8503-dd0c2ed7af8f',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'PYPL',
    name: 'PayPal Holdings, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'ba1cc326-cf8d-4d7c-a49e-8b413555f3d0',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'PANW',
    name: 'Palo Alto Networks, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '840703bb-88cd-4cac-9acd-91eba330dc8a',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'NXPI',
    name: 'NXP Semiconductors N.V. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '596b0016-1d8d-4e2e-9ab3-bfe7514b6be8',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'CHTR',
    name: 'Charter Communications, Inc. Class A Common Stock New',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '4ce9353c-66d1-46c2-898f-fce867ab0247',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'NVDA',
    name: 'NVIDIA Corporation Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'bb2a26c0-4c77-4801-8afc-82e8142ac7b8',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'NFLX',
    name: 'Netflix, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '77832354-b542-4769-b168-1ee930e2d2e9',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'ILMN',
    name: 'Illumina, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'f801f835-bfe6-4a9d-a6b1-ccbb84bfd75f',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'AMZN',
    name: 'Amazon.com, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '1ef18995-5094-4f62-a5c5-e00168611152',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'MU',
    name: 'Micron Technology, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '2ac633b5-b3a7-4ba6-975d-f0f1e12dd1e4',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'ADBE',
    name: 'Adobe Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '403113aa-7838-4345-dd32-d63a5f9da70b',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'ABNB',
    name: 'Airbnb, Inc. Class A Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 40,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '1f888138-e413-4939-b16b-bdd08bb4debd',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'COST',
    name: 'Costco Wholesale Corporation Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'b6d1aa75-5c9c-4353-a305-9e2caa1925ab',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'MSFT',
    name: 'Microsoft Corporation Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '723c21be-11af-4450-9b64-20346a6905fc',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'MRVL',
    name: 'Marvell Technology, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'b02df0cc-0a0a-4ecb-8e92-201b1044ea21',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'MRNA',
    name: 'Moderna, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 60,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '036f74ce-5de5-4718-bc41-1f89caba4388',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'MDB',
    name: 'MongoDB, Inc. Class A Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '31aa3cfa-8925-4cbc-98bc-74f411b7f17c',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'LULU',
    name: 'lululemon athletica inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'cbf869d9-873b-426a-bdea-37e0bc4250f9',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'LIN',
    name: 'Linde plc Ordinary Shares',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '88623995-d3b2-41ff-b80d-17a29c51454b',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'KDP',
    name: 'Keurig Dr Pepper Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'c1fe01e7-c9b1-4b92-8c7a-32153021367e',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'KLAC',
    name: 'KLA Corporation Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'bce94a21-f7e5-4e99-a2f4-9d76514742c4',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'PDD',
    name: 'PDD Holdings Inc. American Depositary Shares',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '4708c2d8-f738-4137-b3b8-c58c7559c053',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'LRCX',
    name: 'Lam Research Corporation Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '705ec4dc-73b9-42fc-8b17-d4e13c31cfae',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'MDLZ',
    name: 'Mondelez International, Inc. Class A Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'c85841d1-e05b-4f3c-9e9c-cc8fd3949fbb',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'MELI',
    name: 'MercadoLibre, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '3988b92e-b5ee-449e-a83a-a04bbdf18cff',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'IDXX',
    name: 'IDEXX Laboratories, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '1c7f101c-4c08-46e9-9f79-60ca13c07e51',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'CTSH',
    name: 'Cognizant Technology Solutions Corporation Class A Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '201b268b-cde8-4010-9fe3-41d2ac7f1e9c',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'AMGN',
    name: 'Amgen Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'edc751a9-e628-40bd-9498-23ad7918269e',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'MCHP',
    name: 'Microchip Technology Incorporated Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'b56defb4-e3f6-4756-ba80-143862d2dda1',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'ON',
    name: 'ON Semiconductor Corporation Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'c73e2c28-af3f-4f5d-b550-a56b567ed47c',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'ORLY',
    name: "O'Reilly Automotive, Inc. Common Stock",
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'd5f668a3-682f-474a-84e2-d340593dd94c',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'BKR',
    name: 'Baker Hughes Company Class A Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'f48fc899-5da1-4687-a23b-515752d5e917',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'HON',
    name: 'Honeywell International Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'aaaaa8a6-79b2-4090-95df-45276d1f4d74',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'PAYX',
    name: 'Paychex, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'c50070cd-18b4-4f29-ae0f-f192e4cc4553',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'BKNG',
    name: 'Booking Holdings Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '03fb07bb-5db1-4077-8dea-5d711b272625',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'AMD',
    name: 'Advanced Micro Devices, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'b0b6dd9d-8b9b-48a9-ba46-b9d54906e415',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'AAPL',
    name: 'Apple Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '39be1334-06b6-4df2-a2f1-b21b942628d0',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'QCOM',
    name: 'QUALCOMM Incorporated Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '61f340d1-ed59-405d-ad94-8f2ec9d470ea',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'CTAS',
    name: 'Cintas Corporation Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'b8dd0cc3-7658-4c38-9c06-215c3377956e',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'CSX',
    name: 'CSX Corporation Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '69b15845-7c63-4586-b274-1cfdfe9df3d8',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'GOOGL',
    name: 'Alphabet Inc. Class A Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'f30d734c-2806-4d0d-b145-f9fade61432b',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'GOOG',
    name: 'Alphabet Inc. Class C Capital Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '23e965be-de5f-44cd-8e2c-b4fbbea0ec9c',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'ROP',
    name: 'Roper Technologies, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'adcce409-1666-4ceb-89fa-ecbb458c18ea',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'ROST',
    name: 'Ross Stores, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: 'aa222c8c-5f60-4b88-bc73-7aaadf424628',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'GILD',
    name: 'Gilead Sciences, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '0a7deac5-2d75-4e54-9f66-51c1c6fad55b',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'SBUX',
    name: 'Starbucks Corporation Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '7a8b4fcf-0622-47ef-8541-de7f70ffc0c4',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'AVGO',
    name: 'Broadcom Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
  {
    id: '2b7d41ee-36a4-4c7e-b783-896568c61ed0',
    class: 'us_equity',
    exchange: 'NASDAQ',
    symbol: 'FTNT',
    name: 'Fortinet, Inc. Common Stock',
    status: 'active',
    tradable: true,
    marginable: true,
    maintenance_margin_requirement: 30,
    shortable: true,
    easy_to_borrow: true,
    fractionable: true,
    attributes: ['fractional_eh_enabled', 'has_options'],
  },
];

export function getAssets() {
  return assets;
}
